### ISSUE TITLE
Can not edit material after importing a project from CalBack

### ISSUE THREAD

**Issue by ucprc-user** [ucdavis/UCPRC-CalME-Issues#9]
CalME user: 

After importing from CalBack, need to change the subgrade, but the "edit" link for all layers are grayed out.

**Comment by RongzongWu** [comment]
![image](https://user-images.githubusercontent.com/52839022/158876826-8a154413-d4c9-4826-aca8-6b516dd66f7b.png)

**Comment by RongzongWu** [comment]
Understood, but there is one exception to this rule, which is the subgrade. I was allowed to change the subgrade since the importing process does NOT specify which subgrade material to use.
